### ISSUE TITLE
Apresentação final 

### ISSUE THREAD

**Issue by Jvbrogni** [KauaGrathwohl/LocaSatc#10]
Montar com os dados e informações conseguidas a apresentação final. @Jvbrogni

**Comment by Jvbrogni** [comment]
Esperando o dicionário de dados para finalizar essa etapa.

**Comment by KauaGrathwohl** [comment]
Dicionário de dados corrigido , conforme correções feitas no modelo físico.

**Comment by Jvbrogni** [comment]
Atualizada a apresentação e o relatório final.
