### ISSUE TITLE
Dicionário de Dados

### ISSUE THREAD

**Issue by Jvbrogni** [KauaGrathwohl/LocaSatc#6]
Preencher com as informações do banco solicitadas pelo dicionário. @gosttavo @KauaGrathwohl

**Comment by KauaGrathwohl** [comment]
Dicionário preenchido e adicionado o link ao README do projeto, issue finalizada.

**Comment by Jvbrogni** [comment]
@KauaGrathwohl devido a atualização do modelo fisico, favor atualizar o dicionário.
