### ISSUE TITLE
Perguntas e regras de negócio

### ISSUE THREAD

**Issue by Jvbrogni** [KauaGrathwohl/LocaSatc#8]
Realizar as perguntas, repostas e as regras de negócio. @KauaGrathwohl @gosttavo

**Comment by KauaGrathwohl** [comment]
Perguntas criadas e adicionadas ao projeto, ainda iremos realizar as consultas

**Comment by KauaGrathwohl** [comment]
Adicionei as consultas conforme necessário.

**Comment by gosttavo** [comment]
testando as regras de negócio
